### Comprobar usuario
POST localhost:8080/api/v1/user/check
Content-Type: application/json

{
  "phone": "987654321",
  "name": "Juan Sebastian"
}

###  Todos los productos
GET localhost:8080/api/v1/product/all

### Pedido por id
POST localhost:8080/api/v1/order/id
Content-Type: application/json

{
  "id": "64524852ce254ce6dda8ce52"
}

### Nuevo pedido
POST localhost:8080/api/v1/order/new
Content-Type: application/json

{
  "productos": [
    {
      "nombre": "Pan integral con frutos secos (arandanos, nuez y ajonjoli)",
      "precio": 2500,
      "cantidad": 1
    }
  ],
  "cliente": "34633112163"
}

### Estado del pedido
POST localhost:8080/api/v1/order/state
Content-Type: application/json

{
  "id": "64524852ce254ce6dda8ce52",
  "estado": "EN COCINA"
}