### Comprobar usuario
POST localhost:8080/api/v1/user/check
Content-Type: application/json

{
  "phone": "987654321",
  "name": "Juan Sebastian"
}

###  Todos los productos
GET localhost:8080/api/v1/product/all

### Constultar estado Pedido por id
GET localhost:8080/api/v1/order/state/6479bc23f863a63d1fb630b0

### Constultar pedido por id
GET localhost:8080/api/v1/order/6479bc23f863a63d1fb630b0

### Nuevo pedido
POST localhost:8080/api/v1/order/new
Content-Type: application/json

{
  "productos": [
    {
      "nombre": "Pan integral con frutos secos (arandanos, nuez y ajonjoli)",
      "precio": 2500,
      "cantidad": 2
    }
  ],
  "cliente": "34633112163"
}

### CAMBIAR Estado del pedido
POST localhost:8080/api/v1/order/state
Content-Type: application/json

{
  "id": "6479bc23f863a63d1fb630b0",
  "estado": "EN COCINA"
}

### Todos los pedidos
GET localhost:8080/api/v1/order/all

### Stock
GET localhost:8080/api/v1/stock/all